/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from "./lib";
export type { lib };
export type { Booster } from "./Booster";
export type { Collection } from "./Collection";
export type { Main } from "./Main";
export type { MarketPlace } from "./MarketPlace";
