/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MainInterface extends utils.Interface {
  functions: {
    "createCollection(string,string,string[])": FunctionFragment;
    "getAllCardsFromBlockChain()": FunctionFragment;
    "getAllCollectionNames()": FunctionFragment;
    "getCollectionFromId(uint256)": FunctionFragment;
    "getCollectionFromName(string)": FunctionFragment;
    "getCollectionIdFromName(string)": FunctionFragment;
    "getMarketPlace()": FunctionFragment;
    "getNbCollections()": FunctionFragment;
    "nbCollections()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createCollection"
      | "getAllCardsFromBlockChain"
      | "getAllCollectionNames"
      | "getCollectionFromId"
      | "getCollectionFromName"
      | "getCollectionIdFromName"
      | "getMarketPlace"
      | "getNbCollections"
      | "nbCollections"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCardsFromBlockChain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCollectionNames",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionFromId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionFromName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionIdFromName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketPlace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNbCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nbCollections",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCardsFromBlockChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCollectionNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionFromId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionFromName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionIdFromName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketPlace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNbCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nbCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Main extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MainInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      uniqCards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllCardsFromBlockChain(overrides?: CallOverrides): Promise<[string[]]>;

    getAllCollectionNames(overrides?: CallOverrides): Promise<[string[]]>;

    getCollectionFromId(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getCollectionFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getCollectionIdFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMarketPlace(overrides?: CallOverrides): Promise<[string]>;

    getNbCollections(overrides?: CallOverrides): Promise<[BigNumber]>;

    nbCollections(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createCollection(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    uniqCards: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllCardsFromBlockChain(overrides?: CallOverrides): Promise<string[]>;

  getAllCollectionNames(overrides?: CallOverrides): Promise<string[]>;

  getCollectionFromId(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getCollectionFromName(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  getCollectionIdFromName(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMarketPlace(overrides?: CallOverrides): Promise<string>;

  getNbCollections(overrides?: CallOverrides): Promise<BigNumber>;

  nbCollections(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      uniqCards: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getAllCardsFromBlockChain(overrides?: CallOverrides): Promise<string[]>;

    getAllCollectionNames(overrides?: CallOverrides): Promise<string[]>;

    getCollectionFromId(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getCollectionFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getCollectionIdFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketPlace(overrides?: CallOverrides): Promise<string>;

    getNbCollections(overrides?: CallOverrides): Promise<BigNumber>;

    nbCollections(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      uniqCards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllCardsFromBlockChain(overrides?: CallOverrides): Promise<BigNumber>;

    getAllCollectionNames(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectionFromId(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollectionFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollectionIdFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketPlace(overrides?: CallOverrides): Promise<BigNumber>;

    getNbCollections(overrides?: CallOverrides): Promise<BigNumber>;

    nbCollections(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      uniqCards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllCardsFromBlockChain(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllCollectionNames(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionFromId(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionIdFromName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketPlace(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNbCollections(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nbCollections(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
