/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace MarketPlace {
  export type ValidateTradeStruct = {
    tokenId: PromiseOrValue<BigNumberish>;
    collectionId: PromiseOrValue<BigNumberish>;
    owner: PromiseOrValue<string>;
  };

  export type ValidateTradeStructOutput = [BigNumber, BigNumber, string] & {
    tokenId: BigNumber;
    collectionId: BigNumber;
    owner: string;
  };

  export type TradeStruct = {
    uri: PromiseOrValue<string>;
    collectionId: PromiseOrValue<BigNumberish>;
    owner: PromiseOrValue<string>;
  };

  export type TradeStructOutput = [string, BigNumber, string] & {
    uri: string;
    collectionId: BigNumber;
    owner: string;
  };

  export type CardStruct = {
    id: PromiseOrValue<string>;
    collectionId: PromiseOrValue<BigNumberish>;
    acceptedCurrencies: PromiseOrValue<string>[];
    owner: PromiseOrValue<string>;
    done: PromiseOrValue<boolean>;
    acceptedCurrency: MarketPlace.TradeStruct;
    spotId: PromiseOrValue<BigNumberish>;
  };

  export type CardStructOutput = [
    string,
    BigNumber,
    string[],
    string,
    boolean,
    MarketPlace.TradeStructOutput,
    BigNumber
  ] & {
    id: string;
    collectionId: BigNumber;
    acceptedCurrencies: string[];
    owner: string;
    done: boolean;
    acceptedCurrency: MarketPlace.TradeStructOutput;
    spotId: BigNumber;
  };
}

export interface MarketPlaceInterface extends utils.Interface {
  functions: {
    "addCollection(uint256,address)": FunctionFragment;
    "aliveTrades()": FunctionFragment;
    "buyCard(uint256,string,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "seeMarketPlace()": FunctionFragment;
    "sellCard(string,uint256,string[])": FunctionFragment;
    "tradesCount()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unSellCard(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addCollection"
      | "aliveTrades"
      | "buyCard"
      | "owner"
      | "renounceOwnership"
      | "seeMarketPlace"
      | "sellCard"
      | "tradesCount"
      | "transferOwnership"
      | "unSellCard"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCollection",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "aliveTrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyCard",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seeMarketPlace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellCard",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tradesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unSellCard",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aliveTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeMarketPlace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tradesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unSellCard", data: BytesLike): Result;

  events: {
    "Exchange(tuple,tuple)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Exchange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface ExchangeEventObject {
  soldCard: MarketPlace.ValidateTradeStructOutput;
  acceptedTrade: MarketPlace.ValidateTradeStructOutput;
}
export type ExchangeEvent = TypedEvent<
  [
    MarketPlace.ValidateTradeStructOutput,
    MarketPlace.ValidateTradeStructOutput
  ],
  ExchangeEventObject
>;

export type ExchangeEventFilter = TypedEventFilter<ExchangeEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface MarketPlace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketPlaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCollection(
      collectionId: PromiseOrValue<BigNumberish>,
      collection: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    aliveTrades(overrides?: CallOverrides): Promise<[BigNumber]>;

    buyCard(
      spotId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    seeMarketPlace(
      overrides?: CallOverrides
    ): Promise<[MarketPlace.CardStructOutput[]]>;

    sellCard(
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      acceptedCurrency: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tradesCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unSellCard(
      spotId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addCollection(
    collectionId: PromiseOrValue<BigNumberish>,
    collection: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  aliveTrades(overrides?: CallOverrides): Promise<BigNumber>;

  buyCard(
    spotId: PromiseOrValue<BigNumberish>,
    uri: PromiseOrValue<string>,
    collectionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  seeMarketPlace(
    overrides?: CallOverrides
  ): Promise<MarketPlace.CardStructOutput[]>;

  sellCard(
    uri: PromiseOrValue<string>,
    collectionId: PromiseOrValue<BigNumberish>,
    acceptedCurrency: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tradesCount(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unSellCard(
    spotId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addCollection(
      collectionId: PromiseOrValue<BigNumberish>,
      collection: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    aliveTrades(overrides?: CallOverrides): Promise<BigNumber>;

    buyCard(
      spotId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    seeMarketPlace(
      overrides?: CallOverrides
    ): Promise<MarketPlace.CardStructOutput[]>;

    sellCard(
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      acceptedCurrency: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    tradesCount(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unSellCard(
      spotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Exchange(tuple,tuple)"(
      soldCard?: null,
      acceptedTrade?: null
    ): ExchangeEventFilter;
    Exchange(soldCard?: null, acceptedTrade?: null): ExchangeEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    addCollection(
      collectionId: PromiseOrValue<BigNumberish>,
      collection: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    aliveTrades(overrides?: CallOverrides): Promise<BigNumber>;

    buyCard(
      spotId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    seeMarketPlace(overrides?: CallOverrides): Promise<BigNumber>;

    sellCard(
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      acceptedCurrency: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tradesCount(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unSellCard(
      spotId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCollection(
      collectionId: PromiseOrValue<BigNumberish>,
      collection: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    aliveTrades(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyCard(
      spotId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    seeMarketPlace(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellCard(
      uri: PromiseOrValue<string>,
      collectionId: PromiseOrValue<BigNumberish>,
      acceptedCurrency: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tradesCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unSellCard(
      spotId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
